# Generated by Django 5.1.1 on 2024-09-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='band_members', to='performer.artist'),
        ),
    ]
