# Generated by Django 5.1.1 on 2024-09-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0002_alter_band_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='members',
        ),
    ]
