# Generated by Django 5.1.1 on 2024-09-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0003_remove_band_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='formation_date',
        ),
        migrations.AddField(
            model_name='band',
            name='formation_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
