# Generated by Django 5.1.1 on 2024-09-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='musics', to='album.album'),
        ),
    ]
