# Generated by Django 5.1.1 on 2024-09-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
